### PR TITLE
add basic option parsing for nstars

### PR DESCRIPTION
**Pull request by livibetter**
Please check if anything need to edit/rename or move around.

I noticed that there is inconsistence of coding style in `sstar.c` and `xstar.c`, e.g. the space gap after function name and/or inside of parentheses. I decided to go with `nstar.c`'s style.

### CODE REVIEW

**Comment by livibetter** [comment]
Related issue #2.

**Comment by ph1l** [comment]
Yea, my coding style in C is pretty horrific. To be honest, this is one of the first things I wrote in C.

**Comment by ph1l** [comment]
This looks like a fair enough start, but as it's submitted, it doesn't add much value yet, what sort of arguments do you think would be desired?

**Comment by livibetter** [comment]
char and color modes, for nstars anyway. For the other two frontends, sleep, size, etc., but I will leave those to others.

**Comment by ph1l** [comment]
Okay. Please submit a pull request for nstars only. Leave the other frontends as-is if you do not intend to add any options besides basic plumbing.

Thanks!

**Comment by livibetter** [comment]
Done. I did a force update, so it would be a clean commit. I'll prefer this gets merged first, then I open another PR with two commits for `-s` star character and `-c` color mode after I finish `/colormode`, which is what I am going to make another PR for in the meantime.

**Review by ph1l — APPROVED** [review]

**Pull request merged**
